AWSTemplateFormatVersion: 2010-09-09
Description: |
  IAM role for Cresta Amazon Connect Data Access. It uses External ID for third party access.
  More information: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html
Parameters:
  SourceBucketName:
    Description: >-
      The contents of this bucket will be shared with Cresta. 
      This is the S3 bucket holding the recordings / transcriptions
    Type: String
    AllowedPattern: .+
    ConstraintDescription: BucketName is required
  ConnectInstanceId:
    Description: >-
      The ID of the Amazon Connect Instance
    Type: String
    AllowedPattern: .+
    ConstraintDescription: ConnectInstanceId is required
  ExternalId:
    Description: >-
      External ID for the data access role (ask your Cresta account manager)
    Type: String
    AllowedPattern: .+
    ConstraintDescription: ExternalId is required
  IAMRoleName:
    Description: Customize the name of IAM role for ingesting/sending data to Cresta
    Type: String
    Default: CrestaIngestionRole
  CrestaAWSAccountIds:
    Description: >-
      Comma separated list of AWS account IDs allowed to assume the IAM role. DO NOT CHANGE!
    Type: CommaDelimitedList
    Default: 510370324380,488350602631,730335187493,975050116558,302217641952,107136125828
Resources:
  CrestaIngestionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Split
                - ","
                - !Sub
                  - arn:aws:iam::${account}:root
                  - account: !Join
                      - ":root,arn:aws:iam::"
                      - !Ref CrestaAWSAccountIds
            Action:
              - "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref ExternalId
      RoleName: !Ref IAMRoleName
      Policies:
        - PolicyName: CrestaPostcallAccessS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Resource:
                - !Sub "arn:aws:s3:::${SourceBucketName}"
                - !Sub "arn:aws:s3:::${SourceBucketName}/*"
              Action:
                - "s3:Get*"
                - "s3:List*"
        - PolicyName: CrestaPostcallAccessConnect
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: 
                  - !Sub "arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}"
                  - !Sub "arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}/*"
                Action:
                  - "connect:ListQueues"
                  - "connect:ListUsers"
                  - "connect:SearchUsers"
                  - "connect:DescribeUser"
                  - "connect:DescribeContact"
                  - "connect:SearchContacts"
                  - "connect:ListInstanceStorageConfigs"
Outputs:
  ExternalId:
    Description: External ID for the data access role
    Value: !Ref ExternalId
  SourceBucketName:
    Description: S3 Bucket with source data for transfer
    Value: !Ref SourceBucketName
  IAMRoleName:
    Description: AWS IAM Role named to be used with Cresta Data Ingestion
    Value: !Ref CrestaIngestionRole
  AccountId:
    Description: AWS Account number
    Value: !Ref "AWS::AccountId"
  RoleArn:
    Description: Arn of Created Role
    Value: !GetAtt CrestaIngestionRole.Arn
  Region:
    Description: AWS Region
    Value: !Ref "AWS::Region"
