name: cfn-lint
on:
  - push
jobs:
  cfn-lint:
    runs-on:
      group: self-hosted
      labels: cpu

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: cfn-lint
      uses: scottbrenner/cfn-lint-action@v2.4.6
      with:
        args: "**/*.yaml"
